{
 "title": "Flowspec Solutions - NETFLOW - BIGTECHs",
 "tags": [
  "netflow",
  "flowspec"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Header Executivo",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Tráfego Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Pacotes Totais",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.packets", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fluxos Totais",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Big Tech/CDN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "(source.as.organization.name:\"Facebook, Inc.\") OR (source.as.organization.name:\"Google LLC\") OR (source.as.organization.name:\"Bytedance Inc.\" OR source.as.organization.name:\"ByteDance Inc.\") OR (source.as.organization.name:\"Amazon.com, Inc.\") OR (source.as.organization.name:\"Akamai International B.V.\") OR (source.as.organization.name:\"Globo Comunicacao e Participacoes SA\") OR (source.as.organization.name:\"Cloudflare, Inc.\") OR (source.as.organization.name:\"Fastly, Inc.\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Big Techs & CDNs",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Facebook",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Facebook, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Google",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Google LLC\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "ByteDance",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Bytedance Inc.\" OR source.as.organization.name:\"ByteDance Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Amazon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Amazon.com, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Akamai",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Akamai International B.V.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Globo",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Globo Comunicacao e Participacoes SA\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Cloudflare",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Cloudflare, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fastly",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Fastly, Inc.\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Evolução do Consumo",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 23 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Facebook",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Facebook, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Google",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Google LLC\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "ByteDance",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Bytedance Inc.\" OR source.as.organization.name:\"ByteDance Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Amazon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Amazon.com, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Akamai",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Akamai International B.V.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Globo",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Globo Comunicacao e Participacoes SA\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Cloudflare",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Cloudflare, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fastly",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Fastly, Inc.\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ranking por Volume",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 23 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Facebook",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Facebook, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Google",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Google LLC\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "ByteDance",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Bytedance Inc.\" OR source.as.organization.name:\"ByteDance Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Amazon",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Amazon.com, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Akamai",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Akamai International B.V.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Globo",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Globo Comunicacao e Participacoes SA\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Cloudflare",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Cloudflare, Inc.\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Fastly",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.as.organization.name:\"Fastly, Inc.\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 37 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Source IP",
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "12" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Destination IP",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 37 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Destination IP",
     "bucketAggs": [
      {
       "field": "destination.ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "12" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Regiões",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 37 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Regiões",
     "bucketAggs": [
      {
       "field": "source.geo.region_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Portas",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 56 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "alias": "Portas",
     "bucketAggs": [
      {
       "field": "destination.port",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Leitura Executiva",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 56 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}